name: deliverzler
description: Delivery App for Restaurants built on Flutter using Domain-Driven Design (DDD) and Riverpod Framework.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.2.0

  # StateManagement & DI
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # FP
  fpdart: ^1.1.1
  rxdart: ^0.28.0

  # Connectivity
  connectivity_plus: ^4.0.1

  # Routing
  go_router: ^12.1.1

  # Location
  location: ^8.0.0
  geolocator: ^13.0.3
  google_maps_flutter: ^2.12.1
  flutter_polyline_points: ^2.1.0

  # Apis
  dio: ^5.8.0+1

  # Firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_app_check: ^0.3.2+4

  # LocalStorage
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  flutter_cache_manager: ^3.4.1
  image_picker: ^0.8.7+5

  # Images
  cached_network_image: ^3.4.1
  lottie: ^2.3.2

  # Utils
  flutter_dotenv: ^5.2.1
  mocktail: ^0.3.0
  device_info_plus: ^9.0.3
  fast_immutable_collections: ^9.1.5
  flutter_fadein: ^2.0.0
  uuid: ^4.4.2
  url_launcher: ^6.1.11
  flutter_local_notifications: ^19.0.0
  timeago: ^3.4.0
  flutter_timezone: ^4.1.0
  permission_handler: ^11.4.0

  # Widgets
  flutter_platform_widgets: ^6.0.2
  flutter_adaptive_scaffold: ^0.1.6
  fluttertoast: ^8.2.2
  qr_flutter: ^4.1.0
  material_floating_search_bar:
    git:
      url: https://github.com/Railway-Engineering-Solutions/material_floating_search_bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  import_sorter: ^4.6.0

  # Lints
  very_good_analysis: ^5.1.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.3.4

  # Code gen
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  go_router_builder: ^2.8.2

import_sorter:
  comments: false

flutter:
  uses-material-design: true

  generate: true # Enable generation for localizations

  assets:
    - assets/map_styles/
    - assets/icons/
    - assets/icons/dialog_widget_icons/
    - assets/icons/languages_icons/
    - assets/icons/screens_icons/
    - assets/images/core/
    - assets/images/login/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
